Dugk 54 convert to react tabs
Omarley7/DTaaS-Bachelor-new-GUI pull request #38
Opened 2023-04-03 12:50 UTC by DaloonOfDoom

2023-04-03 13:30 UTC, SyntaxXeror approved these changes
LGTM 🤠🔫

2023-04-03 13:32 UTC, Omarley7 commented
```bash
warning " > styled-components@5.3.9" has unmet peer dependency "react-is@>= 16.8.0".
```

Please install missing dependency

2023-04-03 15:01 UTC, Omarley7 commented
Workbench unittest test failing, likely to be a `<div>` inside a `<p>`

2023-04-06 11:25 UTC, Omarley7 commented
Looks great few notes, we should take with us in the next PR:
- UI looks very different compared to MUI
- Should really also have a test for the `creatTabdata()` function

2023-04-06 11:29 UTC, Omarley7 requested changes

2023-04-06 11:29 UTC, Omarley7 commented on client/test/unitTests/Components/TabComponent.test.tsx
Could add a few more test cases:
- What happens if no tabs are provided?
- A test case for the createTabData function

2023-04-10 09:54 UTC, Omarley7 approved these changes
nice update

2023-04-10 10:16 UTC, merged